- Cargo.lock
- Cargo.toml
- src/host_triple.rs
- src/lib.rs
- src/main.rs
- src/targets.rs
- src/toolchain/gcc_toolchain.rs
- src/toolchain/llvm_toolchain.rs
- src/toolchain/rust_toolchain.rs
This argument is [also present on rustup](https://rust-lang.github.io/rustup/installation/other.html?highlight=default-host#other-installation-methods) and it would be necessary for #9 and #10.
> Add `default-host` argument

- src/toolchain/espidf.rs
- src/toolchain/gcc_toolchain.rs
- src/toolchain/llvm_toolchain.rs
- src/toolchain/mod.rs
- src/toolchain/rust_toolchain.rs
- Reuse GCC if installed for the target
- Reuse LLVM if installed
- Improve how paths are printed
> Check if GCC or LLVM are installed, if so, reuse them.

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/host_triple.rs
- src/lib.rs
- src/main.rs
- src/targets.rs
- src/toolchain/espidf.rs
- src/toolchain/gcc_toolchain.rs
- src/toolchain/llvm_toolchain.rs
- src/toolchain/rust_toolchain.rs
- Adds an `espup.toml` configuration file where we store what we have installed, so it's easier to update/uninstall.
- Update `uninstall` and `update` subcommands.
> Add configuration file

- README.md
- src/toolchain/rust_toolchain.rs
- If `rustup` is not installed throw an error with a reference to the installation website.
- Document that `rustup` should be installed
This change was discussed in #10 and would solve both #10 and #9
> Add `rustup` as a requirement

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/main.rs
- src/toolchain/rust.rs
- Get the latest Xtensa Rust toolchain version from the latest release of `rust-build` repo.
- If no version is provided to the `update` and `install` subcommand is provided, it will use the latest.
- Add unit test for `XtensaRust::parse_version`
> Avoid using hardcoded Xtensa Rust version 

- README.md
I added perl to dependencies on fedora, else the compilation of espup fails
> Add perl to the fedora dependencies

- src/main.rs
- src/targets.rs
- src/toolchain/gcc.rs
Nothing ground-breaking here, just some small tweaks. Also fixed some of the doc comments in the `Target` enum which weren't quite right.
> Add ESP32-C2 to list of recognized targets, simplify some code

- .github/workflows/ci.yaml
I've also added [94376da](https://github.com/esp-rs/espup/pull/41/commits/94376da073df14719bd542e5af5a3a138a7f0a78) to avoid running the CI twice in PRs.
> Update CI to run in parallel

- .devcontainer/Dockerfile
- Cargo.lock
- README.md
- src/toolchain/llvm.rs
Update the LLVM version to use the latest release: esp-15.0.0-20221201, which removes the `libtinfo5` dependency.
> Update LLVM release

- src/main.rs
- src/toolchain/gcc.rs
- Windows export file now only contains` \` instead of mixing `/` and `\`.
- GCC paths are now exported between `"` for Unix.
> Fix Windows exports

- src/main.rs
Now, if you enter a wrong `default_host`, the following error will appear:
```
error: 'totally_wrong_host' isn't a valid value for '--default-host <DEFAULT_HOST>'
[possible values: x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu, x86_64-pc-windows-msvc, x86_64-pc-windows-gnu, x86_64-apple-darwin, aarch64-apple-darwin]
```
> Add possibles values to default_host arguments

- README.md
- src/error.rs
- src/main.rs
- Improved `esp-idf-version` documentation
- Improved `profile-minimal` documentation
- Improved `export-file` documentation
- Update usage sections of Readme
- If you provide a wrong path for `export-file` argument, the following error will prompt:
```sh
esp@7f6b5a7b7dc9:~/espup$ cargo r -r -- install -f some_directory/
Compiling espup v0.2.5-dev (/home/esp/espup)
Finished release [optimized] target(s) in 54.01s
Running `target/release/espup install -f some_directory/`
[2022-12-29T13:09:51Z INFO ] 💽  Installing esp-rs
Error: espup::wrong_export_file
× ⛔  Wrong export file destination: 'some_directory/'. Please, use an absolte or releative path (including the file and its extension).
```
See #121 for more details
> Fix install help documentation

- Cargo.lock
- Cargo.toml
- src/config.rs
- src/host_triple.rs
- src/main.rs
- src/targets.rs
- src/toolchain/espidf.rs
- src/toolchain/gcc.rs
- src/toolchain/llvm.rs
- src/toolchain/mod.rs
- src/toolchain/rust.rs
Nothing too interesting here:
- Don't depend directly on `strum_macros`, as it is already pulled in by `strum`'s **derive** feature
- Use the `directories` package instead of using both `dirs` and `directories-next`
- Ironically, `directories` is now more up-to-date than `directories-next`
- Fix some small typos in the output, use more consistent quoting
- Silence the output from invoked script/application when installing Rust
- This looked out of place in the output; there may be other places where this should be done as well
- Might be a good idea to pull in the `indicatif` package and have status spinners for each step in the future?
> Small fixes and cleanup

- src/main.rs
- src/toolchain/rust.rs
- Avoid using hardcoded len for the `mscp`
- For some reason, when using `spawn`, some [CIs were failing ](https://github.com/SergioGasquez/esp-flasher-stub/actions/runs/3895145945/jobs/6650182204). I think what was happening was that the await was completed but the command was still running which lead to some parts of the toolchain not being properly installed.
- This slows down the installation a bit
- The same CI with this changes now works fine https://github.com/SergioGasquez/esp-flasher-stub/actions/runs/3902025238 
I was able to reproduce this issue in the CI and using doing the installation in a Dockerfile but not on host machines and neither on `esp-hal` CI.
I plan to create a new `espup` release once this is fixed, so we can update the rest of the CIs
> Avoid spawning commands

- Cargo.lock
- Cargo.toml
- src/error.rs
- src/main.rs
- src/toolchain/espidf.rs
- src/toolchain/gcc.rs
- src/toolchain/llvm.rs
- src/toolchain/mod.rs
- src/toolchain/rust.rs
- When downloading a file, if the output file is already present, we delete and download it again
- Added a `name` method to the `Installable` trait
- Implemented it for all the components
- Added retries to install
- We now do 3 attempts of installing every component
- We no longer return `Err` if the Xtensa Toolchain is already present. Instead, we reuse the installation, see #138
> Add installation retries

- Cargo.toml
Some users reported having issues on MacOs (#141) with `openssl` so I'm statically linking it for all Unix targets
> Statically link `openssl` for all Unix targets

- src/toolchain/rust.rs
`rust-src-nightly/install.sh` only has one available component `rust-src`: 
```
$ ../.espressif/dist/rust-src/rust-src-nightly/install.sh --list-components
* rust-src
```
So, it does not make any sense to filter `rust-docs-json-preview,rust-docs` components.
>  Improve `rust-src-nightly/install.sh` command

- src/config.rs
- src/main.rs
Just a small tweak. Since collections implement `Default` it's sort of an anti-pattern to wrap them in an `Option` like this, as an empty set and `None` symbolize essentially the same thing in this context. This just cleans up the handling of the extra crates a bit.
~~For some reason the `InstallOpts` struct was being boxed as well, while the other subcommands were not, so I've just changed this.~~
> Simplify handling of extra crates

- src/toolchain/llvm.rs
Fixes #164
CLANG_PATH is relevant for bindgen to be able to find required headers and library files.  Without exporting this along with LIBCLANG_PATH, you'll get a mismatch using bindgen and if the host clang doesn't support full cross compilation of C code (which is common for Ubuntu in my case, at least), then ultimately bindgen will not be able to compile the code its trying to generate bindings for.  The user will see weird errors like basic types int16_t and such are missing or common header files like string.h aren't available.
> Export CLANG_PATH so bindgen works with cross compilation

- src/toolchain/gcc.rs
Hey ! 
This PR makes `espup` download the aarch64 versions of the gcc tools on Macs with arm architecture instead of the x86_64 versions.
> fix: download Mac aarch64 versions of gcc

- Cargo.lock
- Cargo.toml
- README.md
- src/main.rs
Uses `clap_complete` to generate shell completions. Usage example: 
```
espup completions bash > /usr/share/bash-completion/completions/espup.bash
```
> Add support for generating shell completions

- .github/workflows/issue_handler.yml
- Cargo.lock
- Cargo.toml
- README.md
- src/cli.rs
- src/error.rs
- src/lib.rs
- src/main.rs
- src/toolchain/mod.rs
- src/toolchain/rust.rs
- `update` subcommand now basically does the same thing as `install`
- Moved the installing logic to toolchain mod
- Created a `cli` mod
> Rework update subcommand

- src/toolchain/rust.rs
Temporary directories were not properly cleaned after executing `espup`.
> Fix tempdirs cleanup

- src/error.rs
- src/toolchain/gcc.rs
- src/toolchain/llvm.rs
- src/toolchain/mod.rs
- src/toolchain/rust.rs
Check if the `remove_dir_all` fn succeeds, if not, throw a descriptive error.
> Improve `remove_dir_all` errors

- README.md
- src/cli.rs
- src/main.rs
If we provide the full Xtensa Rust version (with `-v/--toolchain_version`) and we use the new flag (-`k/--skip_version_parse`) the `XtensaRust::parse_version()` method, which causes some issues on CI, won't be called.
> Add a flag to skip Xtensa Rust version parsing

- .github/workflows/ci.yaml
- CHANGELOG.md
- src/env.rs
- src/error.rs
- src/lib.rs
- src/toolchain/gcc.rs
- src/toolchain/llvm.rs
- src/toolchain/mod.rs
- src/toolchain/rust.rs
- Add warn message when failed to detect Xtensa Rust
- Format log messages
> Add warn message when failed to detect Xtensa Rust

- README.md
Based on rustup: https://github.com/rust-lang/rustup/blob/master/doc/user-guide/src/installation/index.md#enable-tab-completion-for-bash-fish-zsh-or-powershell
> Update docs regarding tab completion

- src/toolchain/llvm.rs
In Unix systems, it creates a symlink from `$HOME/.espup/esp-clang/` to the directory containing Xtensa clang. This will help `std` projects, as `embuild`, could check if `LIBCLANG_PATH` is set by the user and if its not, it will be defaulted to `$HOME/.espup/esp-clang`, with this we can avoid the usual error of the user forgetting to source the export script.
This is only helpful in `std` approach, for `no_std` it does nothing
> Add symlink to LLVM 

- CHANGELOG.md
- README.md
- src/cli.rs
- src/env.rs
- src/main.rs
- src/toolchain/gcc.rs
- src/toolchain/llvm.rs
- src/toolchain/mod.rs
- src/toolchain/rust.rs
- Fix typo in Readme
- Add some docstrings
- Remove LLVM 15 and 16 when uninstalling
- Change some logs levels to reduce verbosity
- Minor code optimizations
> Minor improvements

- CHANGELOG.md
- Cargo.toml
- README.md
- src/cli.rs
This adds support for specifying the location of the export file via the environment variable `ESPUP_EXPORT_FILE`. So one does not have to remember to explicitly specify `--export-file FILE` when installling or updating with a custom location of that file.
> Allow specifying export file via ESPUP_EXPORT_FILE

- CHANGELOG.md
- README.md
- src/cli.rs
- src/targets.rs
- src/toolchain/mod.rs
- src/toolchain/rust.rs
Draft until `riscv32imafc-unknown-none-elf` is supported as tier 2 target: https://github.com/rust-lang/rust/pull/118704
> Add support for ESP32-P4

- Cargo.lock
- Cargo.toml
Added support for SOCKS5 proxy, which is important for users in China.
> Add socks5 proxy support

- .github/workflows/changelog.yaml
- CHANGELOG.md
- Cargo.lock
- Cargo.toml
- Update dependencies
- Bump espup version
- Add CI to check changelog entries
> Prepare v0.12.0 release 

- CHANGELOG.md
- src/toolchain/llvm.rs
The fix for extended LLVM mode with LLVM 17 accidentally broke it for toolchain versions using LLVM 15 and 16.
> Fix extended LLVM mode for LLVM < 17

- CHANGELOG.md
- src/toolchain/gcc.rs
Use latest GCC release https://github.com/espressif/crosstool-NG/releases/tag/esp-14.2.0_20240906
> Update to GCC 14

- CHANGELOG.md
- src/toolchain/llvm.rs
Testing done inside the devcontainer of espup:
```
cargo r -r -- uninstall
cargo r -r -- install -v 1.81.0.0
cargo r -r -- install -v 1.82.0.0 -l debug
```
Results in the following export file:
```
export PATH="/home/esp/.rustup/toolchains/esp/xtensa-esp-elf/esp-14.2.0_20240906/xtensa-esp-elf/bin:$PATH"
export LIBCLANG_PATH="/home/esp/.rustup/toolchains/esp/xtensa-esp32-elf-clang/esp-18.1.2_20240912/esp-clang/lib"
```
And leaves both llvms installed under `/home/esp/.rustup/toolchains/esp/xtensa-esp32-elf-clang`. Note that 1.81 installs LLVM 17 and 1.82 LLVM 18.
Activating the environment, I was able to build and flash a fresh template for S3.
> Add support for LLVM 18

- CHANGELOG.md
- src/toolchain/rust.rs
related: #480  #458 #397
Issue:
1. case 1:
`rustup toolchain install nightly --profile minimal --component rust-src --target riscv32imc-unknown-none-elf,riscv32imac-unknown-none-elf,riscv32imafc-unknown-none-elf` *OK*
2. case 2:
`rustup toolchain install nightly --profile minimal --component rust-src --target riscv32imc-unknown-none-elf --target riscv32imac-unknown-none-elf --target riscv32imafc-unknown-none-elf` *OK*
3. case 3:
`rustup toolchain install nightly --profile minimal --component rust-src --target riscv32imc-unknown-none-elf riscv32imac-unknown-none-elf riscv32imafc-unknown-none-elf` *FAIL*
> Try fix install failure #480

- CHANGELOG.md
- src/cli.rs
- src/main.rs
- src/toolchain/gcc.rs
- src/toolchain/mod.rs
When compiling a Rust library in a Cmake setup with ESP IDF, you eventually ended up in the scenario where the ESP IDF version of the Crosstools can be different ([esp-14.2.0_20241119](https://github.com/espressif/crosstool-NG/releases/tag/esp-14.2.0_20241119)) than the one `espup` is installing ([esp-14.2.0_20240906](https://github.com/espressif/crosstool-NG/releases/tag/esp-14.2.0_20240906)), with no way of changing it.
This adds the capability of passing the crosstools version and also bumps to latest.
> feat: add Crosstools version parameter and update to latest Crosstools
